const workflowSteps = [
    {
        title: "Upload and extract",
        description:
            "Candidates upload a PDF resume and the platform converts it into structured experience, education, skills, and project data that can power editing and analysis.",
    },
    {
        title: "Analyze and optimize",
        description:
            "The React dashboard compares that resume against a pasted job description or a general best-practice scan, then returns a match score, missing keywords, and actionable AI recommendations.",
    },
    {
        title: "Customize without rebuilding HTML",
        description:
            "Users reorder, hide, or add sections while design changes come from CSS templates or AI-generated layout logic, allowing one-column, two-column, and creative styles to share the same resume markup.",
    },
    {
        title: "Export polished applications",
        description:
            "After tailoring content, the user can generate supporting materials like cover letters, connect portfolio links, and download a refined resume that blends content intelligence with dynamic presentation.",
    },
];

const capabilities = [
    "Single neutral HTML resume structure shared across all designs",
    "Database-backed CSS templates for layouts and visual themes",
    "AI-assisted generation of layout logic and custom CSS on demand",
    "React control panel for uploads, resume editing, and feedback loops",
    "Targeted job-description analysis with match scoring and keyword gaps",
    "Section-level customization including reorder, add, show, and hide actions",
];

export default function Home() {
    return (
        <main className="min-h-screen bg-[radial-gradient(circle_at_top,_#eff6ff,_#f8fafc_38%,_#ffffff_78%)] text-slate-950">
            <section className="mx-auto flex max-w-7xl flex-col gap-12 px-6 py-16 lg:px-10 lg:py-24">
                <div className="grid gap-8 lg:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)] lg:items-start">
                    <div className="space-y-6">
                        <span className="inline-flex rounded-full border border-sky-200 bg-white/70 px-4 py-1 text-xs font-semibold uppercase tracking-[0.3em] text-sky-700 shadow-sm backdrop-blur">
                            Static structure, dynamic design, AI optimization
                        </span>

                        <div className="space-y-4">
                            <h1 className="max-w-4xl text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">
                                A resume platform powered by one HTML foundation and endlessly adaptable CSS layouts.
                            </h1>
                            <p className="max-w-3xl text-lg leading-8 text-slate-600 sm:text-xl">
                                The system keeps a single static resume structure for core sections like the header, experience, education,
                                and skills, while every design variation is applied through CSS templates stored in a database. Instead of
                                maintaining many HTML templates, the platform dynamically reshapes the same content into modern one-column,
                                two-column, or more creative presentations.
                            </p>
                        </div>

                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="rounded-3xl border border-slate-200 bg-white/80 p-6 shadow-sm">
                                <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">Design engine</p>
                                <p className="mt-3 text-base leading-7 text-slate-600">
                                    Layouts and themes are fetched as reusable CSS templates or generated by AI in response to requests
                                    such as “modern two-column” without rewriting the underlying markup.
                                </p>
                            </div>
                            <div className="rounded-3xl border border-slate-200 bg-white/80 p-6 shadow-sm">
                                <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">Intelligence layer</p>
                                <p className="mt-3 text-base leading-7 text-slate-600">
                                    AI helps with layout logic, resume analysis, keyword recommendations, and content improvement so the
                                    platform adapts both presentation and substance.
                                </p>
                            </div>
                        </div>
                    </div>

                    <aside className="rounded-[2rem] border border-slate-200 bg-slate-950 p-8 text-slate-50 shadow-2xl shadow-slate-300/40">
                        <p className="text-sm font-semibold uppercase tracking-[0.3em] text-sky-300">Core capabilities</p>
                        <ul className="mt-6 space-y-4 text-sm leading-7 text-slate-200 sm:text-base">
                            {capabilities.map((capability) => (
                                <li key={capability} className="flex gap-3">
                                    <span className="mt-2 h-2.5 w-2.5 shrink-0 rounded-full bg-sky-400" />
                                    <span>{capability}</span>
                                </li>
                            ))}
                        </ul>
                    </aside>
                </div>

                <section className="grid gap-6 rounded-[2rem] border border-slate-200 bg-white/85 p-8 shadow-xl shadow-slate-200/60 backdrop-blur lg:grid-cols-[0.9fr_1.1fr] lg:p-10">
                    <div className="space-y-4">
                        <p className="text-sm font-semibold uppercase tracking-[0.3em] text-sky-700">End-to-end scenario</p>
                        <h2 className="text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">
                            How the platform works from upload to download.
                        </h2>
                        <p className="text-base leading-8 text-slate-600 sm:text-lg">
                            Users begin by uploading a PDF resume. The system parses the file into structured data, then exposes that data
                            through a React dashboard where they can run targeted job-match analysis or general improvement scans. From there,
                            customization tools let them reorganize sections and instantly preview new visual styles by applying CSS-driven
                            layouts instead of swapping HTML templates.
                        </p>
                    </div>

                    <div className="grid gap-4">
                        {workflowSteps.map((step, index) => (
                            <article
                                key={step.title}
                                className="rounded-3xl border border-slate-200 bg-slate-50 p-5 shadow-sm transition-transform duration-200 hover:-translate-y-0.5"
                            >
                                <div className="flex items-center gap-4">
                                    <span className="inline-flex h-10 w-10 items-center justify-center rounded-2xl bg-sky-600 text-sm font-semibold text-white">
                                        0{index + 1}
                                    </span>
                                    <h3 className="text-lg font-semibold text-slate-900">{step.title}</h3>
                                </div>
                                <p className="mt-4 text-sm leading-7 text-slate-600 sm:text-base">{step.description}</p>
                            </article>
                        ))}
                    </div>
                </section>
            </section>
        </main>
    );
}
